# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyget < Formula
  desc ""
  homepage "https://github.com/pytoolbelt/pyget"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/pytoolbelt/pyget/releases/download/v0.0.1/pyget_Darwin_x86_64.tar.gz"
      sha256 "09d8249dfd80903c7188f63af7914db9da8ed418b81f17b2b6977c7120ee6ff1"

      def install
        bin.install "pyget"
      end
    end
    on_arm do
      url "https://github.com/pytoolbelt/pyget/releases/download/v0.0.1/pyget_Darwin_arm64.tar.gz"
      sha256 "2c0f4e7a3d9d41c7fefdab5a38ee3ff5c02d5884120a7607ab825e534b447a5c"

      def install
        bin.install "pyget"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pytoolbelt/pyget/releases/download/v0.0.1/pyget_Linux_x86_64.tar.gz"
        sha256 "5d982175f99be97b8dd3e22c915bace2131ec29c05509e149671777bfa29b197"

        def install
          bin.install "pyget"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pytoolbelt/pyget/releases/download/v0.0.1/pyget_Linux_arm64.tar.gz"
        sha256 "c24ea9fcf7581e91f7c84ad0d15265cad5c7089c549b79a6d4aa7acf3e41952f"

        def install
          bin.install "pyget"
        end
      end
    end
  end
end
